### ISSUE TITLE
Done?

### ISSUE THREAD

**Issue by Codefeater** [HouJP/kaggle-quora-question-pairs#1]
Did your solution have been archived ?

**Comment by HouJP** [comment]
deep model is on the way

**Comment by pl8787** [comment]
Please see [TextNet](https://github.com/pl8787/textnet-release) and [TextNet-Model](https://github.com/pl8787/textnet-model). For tensorflow version please checkout [MatchZoo](https://github.com/faneshion/MatchZoo).
