### ISSUE TITLE
Question about the architecture figure.

### ISSUE THREAD

**Issue by guotong1988** [HouJP/kaggle-quora-question-pairs#11]
<img width="811" alt="wx20180522-145635 2x" src="https://user-images.githubusercontent.com/4702353/40346812-8de986f8-5dd0-11e8-9169-20c8450950be.png">

The INPUT are two sentences.

The OUTPUT is the match score.

Am I right?

Thank you!@pl8787 @HouJP @ddDragon

**Comment by pl8787** [comment]
Yes, it is a text matching task.
