### ISSUE TITLE
how to run ?

### ISSUE THREAD

**Issue by Tongzhenguo** [HouJP/kaggle-quora-question-pairs#4]
小白看了大神的代码，收获颇多，但是不知道怎么运行起来生成一个submission，求大神指点。

**Comment by HouJP** [comment]
hi, I'm sorry to tell you that I have deleted some code which were not important and only keep the key code. You can not get a submission using this version.

**Comment by xfsm1912** [comment]
So how can we get a submission?

**Comment by pyanh** [comment]
@Tongzhenguo @HouJP I don't know how to run the codes, could you tell me ? Thank you very much!
