### ISSUE TITLE
what's the mean of PowerfulWord?

### ISSUE THREAD

**Issue by SunnyMarkLiu** [HouJP/kaggle-quora-question-pairs#6]
Could you please explain more about PowerfulWord? How does it work?
[PowerfulWord](https://github.com/HouJP/kaggle-quora-question-pairs/blob/master/bin/feature_engineering/statistics.py#L178)

Thanks very much!

**Comment by HouJP** [comment]
To simply speaking, we calculate two probabilities for each word:

1. P1: The probability of label == 1 if the word appeared in both sentences of the question pair.
2. P2: The probability of label == 0 if the word appeared only in one of the sentences of the question pair.

Based on these probabilities:

P(label = 1) = P1(word_1) * P1(word_2) * ...
P(label = 0) = P2(word_1) * P2(word_2) * ...

You can define these probabilities if you think they make sense. Hope the explain can help you.

**Comment by SunnyMarkLiu** [comment]
Thanks a lot. Does it similar to  Bayes Theory?

**Comment by HouJP** [comment]
yeah, just like Naive Bayes.

**Comment by SunnyMarkLiu** [comment]
Thank you very much! It's very clear to me.
